# Generated by Django 4.1.7 on 2023-03-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0004_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
