# Generated by Django 4.1.7 on 2023-03-22 20:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0006_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None),
        ),
    ]
