# Generated by Django 4.1.7 on 2023-03-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0007_baseuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
