# Generated by Django 4.1.7 on 2023-03-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0008_alter_baseuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
