# Generated by Django 4.1.7 on 2023-03-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0009_alter_baseuser_phone_number_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
