version: '3.1'

services: 
    db:
      image: postgres
      restart: always
      ports:
        - "5432:5432"
      volumes:
        -  ./data:/var/lib/postgresql
        
      environment:
        POSTGRES_PASSWORD: 112233
        POSTGRES_USER: user
        POSTGRES_DB: hospital

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    redis:
        image: redis
        restart: always
        ports:
            - 6379:6379