# Generated by Django 4.1.7 on 2023-03-22 20:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='creator',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None),
        ),
        migrations.AlterField(
            model_name='setting',
            name='number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None),
        ),
    ]
