# Generated by Django 4.1.7 on 2023-03-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Educational_History',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
    ]
