# Generated by Django 4.2 on 2023-04-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'permissions': (('can_send_email', 'Can Send Email'),)},
        ),
    ]
