# Generated by Django 4.1.7 on 2023-03-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
