# Generated by Django 4.1.7 on 2023-03-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
