# Generated by Django 4.1.7 on 2023-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default=1, upload_to='blogs'),
            preserve_default=False,
        ),
    ]
