# Generated by Django 4.1.7 on 2023-03-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blogs_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
