# Generated by Django 4.1.7 on 2023-03-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctors_educational_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
