# Generated by Django 4.1.7 on 2023-04-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogs_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Blogs', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Səhifə', 'verbose_name_plural': 'Səhifə'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='author_az',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_az',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_az',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='pub_date_az',
        ),
        migrations.RemoveField(
            model_name='news',
            name='pub_date_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.AddField(
            model_name='blogs',
            name='description_az',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='description_en',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
