# Generated by Django 4.1.7 on 2023-03-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_setting_creator_alter_setting_number1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address1',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='address2',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
