# Generated by Django 4.2 on 2023-04-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact_form_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
