# Generated by Django 4.1.7 on 2023-03-31 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctors_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='updated_at',
        ),
    ]
