# Generated by Django 4.2 on 2023-04-21 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comment_options_rename_author_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 22, 12, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
