# Generated by Django 4.1.7 on 2023-03-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_blogs_created_at_remove_blogs_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
