# Generated by Django 4.1.7 on 2023-04-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blogs_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='educational_History',
            new_name='educational_history',
        ),
        migrations.AddField(
            model_name='doctors',
            name='educational_history_az',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='educational_history_en',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
    ]
