# Generated by Django 4.1.7 on 2023-03-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_doctors_created_at_remove_doctors_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='Educational_History',
            new_name='educational_History',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='Positions',
            new_name='positions',
        ),
    ]
