# Generated by Django 4.2 on 2023-04-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug_az',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
