# Generated by Django 4.2 on 2023-04-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscriber_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'permissions': (('can_send_email', 'Can Send Emails'),)},
        ),
    ]
