# Generated by Django 4.2 on 2023-04-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogs_slug_az_blogs_slug_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='slug_az',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='slug_en',
        ),
    ]
