# Generated by Django 4.1.7 on 2023-03-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_educational_history_doctors_educational_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='phone_number',
            new_name='number',
        ),
    ]
