# Generated by Django 4.1.7 on 2023-04-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_educational_history_doctors_educational_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='educational_history',
            field=models.TextField(default=' ', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='educational_history_az',
            field=models.TextField(default=' ', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='educational_history_en',
            field=models.TextField(default=' ', max_length=10000, null=True),
        ),
    ]
