# Generated by Django 4.1.7 on 2023-04-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_phone_number_doctors_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kateqoryalar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Elaqe', 'verbose_name_plural': 'Əlaqələr'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Hekim', 'verbose_name_plural': 'Hekimler'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Xeberler', 'verbose_name_plural': 'Xeberler'},
        ),
        migrations.AlterModelOptions(
            name='newstag',
            options={'verbose_name_plural': 'NewsTag'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Ayarlar', 'verbose_name_plural': 'Ayarlar'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='creator',
            field=models.CharField(max_length=20, verbose_name='creator'),
        ),
    ]
