# Generated by Django 4.2 on 2023-04-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_subscriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={},
        ),
    ]
