# Generated by Django 4.2 on 2023-04-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_doctors_educational_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('sonuc', models.TextField()),
                ('dosya', models.FileField(blank=True, upload_to='rapor_dosyalari/')),
            ],
        ),
    ]
