# Generated by Django 4.2 on 2023-04-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_blogs_slug_az_remove_blogs_slug_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='location',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
