# Generated by Django 4.1.7 on 2023-03-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
