# Generated by Django 4.2 on 2023-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_setting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='location',
            field=models.URLField(max_length=1000),
        ),
    ]
