# Generated by Django 4.2 on 2023-04-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_analizraporu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalizRaporu',
            new_name='AnalizRaport',
        ),
    ]
