# Generated by Django 4.2 on 2023-04-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'permissions': (('can_send_email', 'Can Send Emails'),)},
        ),
    ]
