# Generated by Django 4.1.7 on 2023-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blogs_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='creator',
            field=models.CharField(max_length=20, verbose_name='Yaradici'),
        ),
    ]
