# Generated by Django 4.1.7 on 2023-03-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
