# Generated by Django 4.1.7 on 2023-04-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_setting_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.ImageField(upload_to='Doctors'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='stories'),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.blogs')),
            ],
        ),
    ]
