# Generated by Django 4.2 on 2023-04-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_analizraporu_analizraport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalizRaport',
        ),
    ]
