# Generated by Django 4.1.7 on 2023-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='session',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
