# Generated by Django 4.2 on 2023-04-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_setting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='slogan',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
