# Generated by Django 4.1.7 on 2023-04-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blogs_options_remove_blogs_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'verbose_name': 'Blog Image', 'verbose_name_plural': 'Blog Images'},
        ),
    ]
