# Generated by Django 4.1.7 on 2023-04-01 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_blogimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='author_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='category_az',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_en',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_az',
            field=models.ImageField(blank=True, null=True, upload_to='news_images'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='news_images'),
        ),
        migrations.AddField(
            model_name='news',
            name='pub_date_az',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='pub_date_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address1_az',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address1_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address2_az',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address2_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='creator_az',
            field=models.CharField(max_length=20, null=True, verbose_name='Yaradici'),
        ),
        migrations.AddField(
            model_name='setting',
            name='creator_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Yaradici'),
        ),
        migrations.AddField(
            model_name='setting',
            name='number1_az',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None),
        ),
        migrations.AddField(
            model_name='setting',
            name='number1_en',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None),
        ),
        migrations.AddField(
            model_name='setting',
            name='number2_az',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None),
        ),
        migrations.AddField(
            model_name='setting',
            name='number2_en',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None),
        ),
    ]
