# Generated by Django 4.1.7 on 2023-03-25 15:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_setting_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='number1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None),
        ),
        migrations.AlterField(
            model_name='setting',
            name='number2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None),
        ),
    ]
