# Generated by Django 4.1.7 on 2023-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_blogs_options_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ln',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
