# Generated by Django 4.1.7 on 2023-04-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_news_author_az_news_author_en_news_category_az_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='creator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='creator_az',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='creator_en',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
