# Generated by Django 4.1.7 on 2023-03-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_setting_number1_alter_setting_number2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='address1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='creator',
            field=models.CharField(max_length=20),
        ),
    ]
