# Generated by Django 4.1.7 on 2023-03-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_setting_ln'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='mn',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
