# Generated by Django 4.1.7 on 2023-03-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_setting_mn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='mn',
        ),
    ]
