# Generated by Django 4.1.7 on 2023-04-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_category_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Şərh'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Əlaqə', 'verbose_name_plural': 'Əlaqələr'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Həkim', 'verbose_name_plural': 'Həkimlər'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Xəbərlər', 'verbose_name_plural': 'Xəbərlər'},
        ),
        migrations.AlterModelOptions(
            name='newstag',
            options={'verbose_name_plural': 'Xəbər etiketi'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Səhifə', 'verbose_name_plural': 'Səhifələr'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Vəzifə', 'verbose_name_plural': 'Vəzifələr'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Tənzimləmə', 'verbose_name_plural': 'Tənzimləmələr'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Hekayə', 'verbose_name_plural': 'Hekayələr'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Etiket'},
        ),
    ]
