# Generated by Django 4.1.7 on 2023-04-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('report_text', models.TextField()),
            ],
        ),
    ]
