# Generated by Django 4.1.7 on 2023-03-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_subject_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='chose_doctor',
        ),
    ]
