# Generated by Django 4.1.7 on 2023-04-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_analizraporu_delete_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalizRaporu',
        ),
    ]
