# Generated by Django 4.1.7 on 2023-03-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(upload_to='media/logo'),
        ),
    ]
