# Generated by Django 4.1.7 on 2023-03-19 17:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_setting_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='fb',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='ig',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='ln',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='tw',
            new_name='twitter',
        ),
        migrations.AlterField(
            model_name='setting',
            name='number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='setting',
            name='number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
