# Generated by Django 4.1.7 on 2023-03-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_fb_setting_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Setting'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='number1',
            field=models.IntegerField(),
        ),
    ]
