# Generated by Django 4.2 on 2023-04-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=200)),
                ('aciklama', models.CharField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('dosya', models.FileField(blank=True, upload_to='rapor_dosyalari/')),
            ],
            options={
                'permissions': (('can_add_raport', 'Can add raport'),),
            },
        ),
    ]
