# Generated by Django 4.2 on 2023-04-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analizraport',
            options={'permissions': [('can_add_raport', 'Rapor ekleme izni')]},
        ),
    ]
