# Generated by Django 4.2 on 2023-04-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raport', '0004_alter_analizraport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analizraport',
            options={'permissions': (('can_add_raport', 'modelCan add raport'),)},
        ),
    ]
